env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
   import/no-extraneous-dependencies: [error, { devDependencies: false, optionalDependencies: false, peerDependencies: false }]
