exports_files(
  [
    "defines.bzl",
    "vars.bzl"
  ],
  licenses = None,
  visibility = ["//visibility:public"],
)

py_binary(
  name = "env",
  srcs = ["env.py"],
  visibility = ["//visibility:public"],
)
