package(default_visibility = ["//visibility:public"])
load("//bzl:vars.bzl", "COPTS", "DEPS", "LINKOPTS")

cc_library(
    name = "sdl",
    hdrs = glob([
        "*.hh",
    ]),
    copts = COPTS,
		deps = DEPS,
    linkopts = LINKOPTS,
    includes = [""],
)