load("//tools/build_rules:rust_docs.bzl", "rust_docs")

package(default_visibility = ["//visibility:public"])

licenses([
    "notice" # MIT
])

rust_docs(
    name = "all_docs",
    deps = [
        "//rust/querier"
    ]
)
